name: asset_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  source_gen: ^1.5.0
  analyzer: ^5.0.0
  yaml: ^3.1.0
  path: ^1.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.0.6
  lints: ^4.0.0
  mockito: ^5.4.3
  test: ^1.16.0

executables:
  generate: bin/generate.dart